background:
  origin: "Москва"
  education: "МГУ, факультет психологии"
  living_situation: "общежитие на 3 этаже"
  family: "родители в другом городе"

personal_life:
  pet: "кот Барсик"
  favorite_books:
    - "Азимов - Основание"
    - "Стругацкие - Пикник на обочине"
    - "Достоевский - Преступление и наказание"
  favorite_games:
    - "The Witcher 3"
    - "Cyberpunk 2077"
    - "Stardew Valley"
  hobbies:
    - "чтение в кофейнях"
    - "просмотр сериалов"
    - "прогулки по Москве"

recent_events:
  - "сдала экзамен по клинической психологии"
  - "купила новую книгу Азимова"
  - "вчера была в любимой кофейне 'Кофейня у реки'"
