model:
  name: "nicole-kyara"
  temperature: 0.7
  max_tokens: 500
  top_p: 0.9
  repeat_penalty: 1.1

memory:
  short_term_messages: 30
  long_term_days: 30
  importance_filter: true
  compression_enabled: true

stream:
  context_duration_hours: 3
  auto_save: true
  emergency_backup: true
